parameters:
- name: goVersion
  displayName: 'Go Version'
  type: string
  default: '1.21.7'
- name: signType
  displayName: 'Sign Type'
  values:
  - 'none'
  - 'test'
  - 'real'
  default: real
- name: testTimeout
  displayName: 'Test Timeout (seconds)'
  type: number
  default: 180
- name: windowsPool
  displayName: 'Windows Pool'
  type: object
  default:
    name: VSEngSS-MicroBuild2022-1ES
    os: windows
- name: linuxPool
  displayName: 'Linux Pool'
  type: object
  default:
    name: AzurePipelines-EO
    demands: ImageOverride -equals AzurePipelinesUbuntu20.04compliantGPT
    os: linux
- name: osxPool
  type: object
  default:
    name: Azure Pipelines
    vmImage: macos-latest
    os: macOS

stages:
- stage: build
  jobs:
  - job: Build
    templateContext:
      outputs:
      - output: pipelineArtifact
        path: $(Build.ArtifactStagingDirectory)
        artifact: drop
        artifactName: $(os)_$(arch)

    strategy:
      matrix:
        windows-x86:
          os: windows
          arch: '386'
          extension: .exe
        windows-amd64:
          os: windows
          arch: amd64
          extension: .exe
        windows-arm64:
          os: windows
          arch: arm64
          extension: .exe
        linux-amd64:
          os: linux
          arch: amd64
          extension: ''
        linux-arm64:
          os: linux
          arch: arm64
          extension: ''
        macos-amd64:
          os: darwin
          arch: amd64
          extension: ''
        macos-arm64:
          os: darwin
          arch: arm64
          platform: osx-x64
          extension: ''

    pool: ${{ parameters.linuxPool }}

    steps:
    - checkout: self
      persistCredentials: true

    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'

    - ${{ if and(ne(variables.signType, 'none'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - task: MicroBuildSigningPlugin@4
        displayName: 'Install Signing Plugin'
        inputs:
          signType: '$(signType)'
          azureSubscription: 'MicroBuild Signing Task (DevDiv)'
          feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
        env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - task: DotNetCoreInstaller@1 # Install .NET 3.1 for ddsign.dll
      displayName: 'Install .NET 3.1'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: DotNetCoreInstaller@1 # Install .NET 7.0 for GitVersion
      displayName: 'Install .NET 7.0'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: PowerShell@2 # Install GitVersion to calculate build versions
      displayName: 'Install GitVersion'
      inputs:
        script: dotnet tool install --global GitVersion.Tool --version "5.*"
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PowerShell@2 # Run GitVersion and generate build variables
      displayName: 'GitVersion'
      inputs:
        script: dotnet-gitversion /output buildserver
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: GoTool@0 # Install the Go tool
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2 # Generate a CGManifest of our dependencies (just in case)
      displayName: 'Generate CGManifest'
      inputs:
        filePath: ./Generate-CGManifest.ps1
        targetType: filePath
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2 # Copy the CGManifest output to staging
      displayName: 'Copy CGManifest Artifacts to Staging'
      inputs:
        Contents: 'cgmanifest.json'
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/cgmanifest/$(os)/$(arch)'

    - task: PowerShell@2 # Format the pipeline start time as a Unix timestamp and expose as a variable
      displayName: 'Set BuildTimestamp variable'
      inputs:
        script: |
          $pipelineStartTime = $env:SYSTEM_PIPELINESTARTTIME
          $buildTimestamp = Get-Date -Date $pipelineStartTime -UFormat %s
          Write-Host "##vso[task.setvariable variable=BuildTimestamp]$buildTimestamp"
        targetType: inline

    - task: PowerShell@2 # Ensure generated files are up to date
      displayName: 'Generate'
      inputs:
        script: make generate-ci
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        GOOS: '$(os)'
        GOARCH: '$(arch)'
        VERSION: '$(GitVersion.SemVer)'
        VERSION_MAJOR: '$(GitVersion.Major)'
        VERSION_MINOR: '$(GitVersion.Minor)'
        VERSION_PATCH: '$(GitVersion.Patch)'
        BUILD_TIMESTAMP: '$(BuildTimestamp)'

    - task: PowerShell@2 # Build the DCP binaries
      displayName: 'Build'
      inputs:
        script: make release
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        GOOS: '$(os)'
        GOARCH: '$(arch)'
        VERSION: '$(GitVersion.SemVer)'
        VERSION_MAJOR: '$(GitVersion.Major)'
        VERSION_MINOR: '$(GitVersion.Minor)'
        VERSION_PATCH: '$(GitVersion.Patch)'
        BUILD_TIMESTAMP: '$(BuildTimestamp)'

    - task: PowerShell@2 # Sign the windows binaries if necessary
      displayName: 'Sign Windows Binaries'
      inputs:
        script: dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /filelist:$env:BUILD_SOURCESDIRECTORY/.azure/pipelines/filelist-windows.xml
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      condition: and(succeeded(), eq(variables.os, 'windows'), eq(variables.signType, 'real'))

    - task: PowerShell@2 # Sign the MacOS binaries if necessary
      displayName: 'Sign MacOS Binaries'
      inputs:
        script: |
          zip -ry $env:ARCHIVE_FILE ./bin/
          dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /file:$env:ARCHIVE_FILE /certs:8023
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        ARCHIVE_FILE: '$(Build.SourcesDirectory)/dcp-darwin.zip'
      condition: and(succeeded(), eq(variables.os, 'darwin'), eq(variables.SignType, 'real'))

    - task: PowerShell@2 # Notarize the MacOS binaries if necessary
      displayName: 'Notarize MacOS Binaries'
      inputs:
        script: |
          dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /file:$env:ARCHIVE_FILE /certs:8020
          unzip -o $env:ARCHIVE_FILE
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        ARCHIVE_FILE: '$(Build.SourcesDirectory)/dcp-darwin.zip'
      condition: and(succeeded(), eq(variables.os, 'darwin'), eq(variables.SignType, 'real'))

    - task: CopyFiles@2 # Copy the build output to the staging directory
      displayName: 'Copy Build Artifacts to Staging'
      inputs:
        Contents: '**'
        SourceFolder: '$(Build.SourcesDirectory)/bin/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build/$(os)/$(arch)'

    - task: CopyFiles@2 # Copy the license file to staging
      displayName: 'Copy License Artifacts to Staging'
      inputs:
        Contents: |
          NOTICE
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build/$(os)/$(arch)'

    - task: DotNetCoreCLI@2 # Build the NuGet package for Arcade
      displayName: 'Package NuGet'
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/.azure/DcpNuGet/DcpNuGet.csproj'
        arguments: -p:TargetPlatform=$(os)-$(arch) -p:BuildDir=$(Build.SourcesDirectory)/bin/ -p:Version=$(GitVersion.SemVer)

    - task: CopyFiles@2 # Copy the nuget files to staging
      displayName: 'Copy NuGet Artifacts to Staging'
      inputs:
        Contents: '*.nupkg'
        SourceFolder: '$(Build.SourcesDirectory)/package/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/nuget/$(os)/$(arch)'

    - task: MicroBuildCleanup@1
      condition: succeededOrFailed()

  - job: MergeArtifacts
    displayName: 'Merge Artifacts'
    templateContext:
      type: artifactJob
      inputs:
      - input: pipelineArtifact
        artifactName: windows_x86
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      - input: pipelineArtifact
        artifactName: windows_amd64
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      - input: pipelineArtifact
        artifactName: windows_arm64
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      - input: pipelineArtifact
        artifactName: linux_amd64
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      - input: pipelineArtifact
        artifactName: linux_arm64
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      - input: pipelineArtifact
        artifactName: darwin_amd64
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      - input: pipelineArtifact
        artifactName: darwin_arm64
        targetPath: $(Build.ArtifactStagingDirectory)/build/
      outputs:
      - output: pipelineArtifact
        targetPath: $(Build.ArtifactStagingDirectory)/build/
        artifactName: build

- stage: test
  dependsOn: []
  jobs:
  - job: Test linux
    pool: ${{ parameters.linuxPool }}
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: make test-ci
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        TEST_CONTEXT_TIMEOUT: ${{ parameters.testTimeout }} # Increase test timeout to deal with slow tests

  - job: Test windows
    pool: ${{ parameters.windowsPool }}
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: make test
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        TEST_CONTEXT_TIMEOUT: ${{ parameters.testTimeout }} # Increase test timeout to deal with slow tests

  - job: Test macos
    pool: ${{ parameters.macPool }}
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: make test
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        TEST_CONTEXT_TIMEOUT: ${{ parameters.testTimeout }} # Increase test timeout to deal with slow tests

- stage: release
  condition: and(notin(variables['Build.Reason'], 'PullRequest'), eq(variables.shouldDeploy, 'true'))
  jobs:
  - deployment: NuGetPublish
    pool: ${{ parameters.windowsPool }}
    environment: '$(environment)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: NuGetCommand@2
            displayName: 'Push NuGet Packages'
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '$(deployFeed)'
  - deployment: ArcadeManifestBuild
    pool: ${{ parameters.windowsPool }}
    environment: '$(environment)'
    dependsOn:
    - NuGetPublish
    variables:
    - group: Publish-Build-Assets
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: DotNetCoreInstaller@1
            displayName: 'Install .NET 7.0'
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: DotNetCoreCLI@2
            displayName: 'Build Arcade Manifest'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/.azure/ArcadeManifest/ArcadeManifest.csproj'
              arguments: -t:GenerateAssetManifest -restore -p:NuGetClientNupkgsDirectoryPath=$(Pipeline.Workspace)/nuget/ -p:NuGetFeed=$(feedName) -p:ArtifactsLogDir=$(Build.ArtifactStagingDirectory)/arcade/ -p:MaestroAccessToken=$(MaestroAccessToken) -p:MaestroApiEndpoint=$(MaestroApiEndpoint) -p:IsReleaseOnlyPackageVersion=$(isReleaseOnlyPackageVersion)
  - deployment: ArcadeManifestPublish
    pool: ${{ parameters.windowsPool }}
    environment: '$(environment)'
    dependsOn:
    - ArcadeManifestBuild
    condition: and(succeeded(), or(eq(variables.environment, 'dcp-production'), eq(variables.environment, 'dcp-staging'), eq(variables.environment, 'dcp-development')))
    variables:
    - group: Publish-Build-Assets
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: DotNetCoreInstaller@1
            displayName: 'Install .NET 7.0'
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: DotNetCoreCLI@2
            displayName: 'Publish Manifest to Arcade'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/.azure/ArcadeManifest/ArcadeManifest.csproj'
              arguments: -t:PublishAssetManifest -p:Version=$(Build.BuildNumber) -p:RepoRoot=$(Build.SourcesDirectory) -p:ManifestsPath=$(Pipeline.Workspace)/AssetManifests -p:BuildAssetRegistryToken=$(MaestroAccessToken) -p:MaestroApiEndpoint=$(MaestroApiEndpoint)
          - task: PowerShell@2
            name: BARSVariables
            displayName: Set BARS Variable
            inputs:
              script: Write-Host "##vso[task.setvariable variable=barBuildId;isOutput=true]$env:BAR_BUILD_ID"
              targetType: inline
            env:
              BAR_BUILD_ID: $(BARBuildId)
  - deployment: ArcadeBuildPromote
    pool: ${{ parameters.windowsPool }}
    environment: '$(environment)'
    dependsOn:
    - ArcadeManifestPublish
    condition: and(succeeded(), or(eq(variables.environment, 'dcp-production'), eq(variables.environment, 'dcp-staging'), eq(variables.environment, 'dcp-development')))
    variables:
    - group: Publish-Build-Assets
    - name: barBuildId
      value: $[ dependencies.ArcadeManifestPublish.outputs['ArcadeManifestPublish.BARSVariables.barBuildId'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreInstaller@1
            displayName: 'Install .NET 7.0'
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: PowerShell@2
            displayName: 'Install Darc'
            inputs:
              script: |
                $darcCliPackageName = 'microsoft.dotnet.darc'
                $versionEndpoint = 'https://maestro-prod.westus2.cloudapp.azure.com/api/assets/darc-version?api-version=2019-01-16'
                $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
                $arcadeServicesSource = 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
                Write-Host "Installing Darc CLI version $darcVersion..."
                Write-Host "dotnet tool install $darcCliPackageName --version $darcVersion --add-source '$arcadeServicesSource' -g"
                & dotnet tool install $darcCliPackageName --version $darcVersion --add-source "$arcadeServicesSource" -g
              targetType: inline
          - task: PowerShell@2
            displayName: 'Promote to Channel'
            inputs:
              script: |
                Write-Host 'darc add-build-to-channel --id "$env:BAR_BUILD_ID" --publishing-infra-version 3 --default-channels --source-branch main --bar-uri $env:MAESTRO_API_ENDPOINT'
                darc add-build-to-channel --id "$env:BAR_BUILD_ID" --publishing-infra-version 3 --default-channels --source-branch main --bar-uri $env:MAESTRO_API_ENDPOINT --password $env:MAESTRO_ACCESS_TOKEN --azdev-pat $env:SYSTEM_ACCESSTOKEN
              targetType: inline
            env:
              BAR_BUILD_ID: $(barBuildId)
              MAESTRO_API_ENDPOINT: $(MaestroApiEndpoint)
              MAESTRO_ACCESS_TOKEN: $(MaestroAccessToken)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
