trigger: none

parameters:
- name: signType
  displayName: 'Sign Type'
  values:
  - 'none'
  - 'test'
  - 'real'
  default: real
- name: testTimeout
  displayName: 'Test Timeout (seconds)'
  type: number
  default: 180

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: common-variables.yml@self

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
    containers:
      linux_build_container:
        image: 'mcr.microsoft.com/oss/go/microsoft/golang:1.23-fips-bullseye'
        options: --name $(BuildContainerName)
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
    stages:
    - template: common-build.yml@self
      parameters:
        signType: ${{ parameters.signType}}
        testTimeout: ${{ parameters.testTimeout}}
