trigger: none

parameters:
- name: goVersion
  displayName: 'Go Version'
  type: string
  default: '1.21.0'
- name: signType
  displayName: 'Sign Type'
  values:
  - 'none'
  - 'test'
  - 'real'
  default: real
- name: testTimeout
  displayName: 'Test Timeout (minutes)'
  type: number
  default: 3
- name: packageNuGet
  displayName: 'Package NuGet(s)'
  type: boolean
  default: true

variables:
  TeamName: 'DCP'
  MaestroApiEndpoint: https://maestro-prod.westus2.cloudapp.azure.com
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    signType: 'none'
    pullRequest: true
  ${{ else }}:
    signType: ${{ parameters.signType }}
    pullRequest: false
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    environment: 'dcp-development'
    deployFeed: '0bdbc590-a062-4c3f-b0f6-9383f67865ee/332dbfb2-0cfc-4ab0-9528-51720db68f63'
    feedName: 'dcp-development'
    shouldDeploy: true
  ${{ elseif startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    environment: 'dcp-staging'
    deployFeed: '0bdbc590-a062-4c3f-b0f6-9383f67865ee/0d6e3604-e79a-4d86-8d1a-4689e01dd01e'
    feedName: 'dcp-staging'
    shouldDeploy: true
  ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/production') }}:
    environment: 'dcp-production'
    deployFeed: '0bdbc590-a062-4c3f-b0f6-9383f67865ee/3686248d-9f4d-4640-8796-f1fab99dcc2d'
    feedName: 'dcp'
    shouldDeploy: true
  ${{ else }}:
    environment: 'dcp-development'

stages:
- stage: build
  jobs:
  - job: Build
    strategy:
      matrix:
        windows-x86:
          os: windows
          arch: '386'
          extension: .exe
        windows-amd64:
          os: windows
          arch: amd64
          extension: .exe
        windows-arm64:
          os: windows
          arch: arm64
          extension: .exe
        linux-amd64:
          os: linux
          arch: amd64
          extension: ''
        linux-arm64:
          os: linux
          arch: arm64
          extension: ''
        macos-amd64:
          os: darwin
          arch: amd64
          extension: ''
        macos-arm64:
          os: darwin
          arch: arm64
          platform: osx-x64
          extension: ''
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      persistCredentials: true

    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'

    - ${{ if and(ne(variables.signType, 'none'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - task: MicroBuildSigningPlugin@4
        displayName: 'Install Signing Plugin'
        inputs:
          signType: '$(signType)'
          azureSubscription: 'MicroBuild Signing Task (DevDiv)'
          feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
        env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - task: DotNetCoreInstaller@1
      displayName: 'Install .NET 3.1'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: DotNetCoreInstaller@1
      displayName: 'Install .NET 7.0'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: PowerShell@2
      displayName: 'Install GitVersion'
      inputs:
        script: dotnet tool install --global GitVersion.Tool --version "5.*"
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PowerShell@2
      displayName: 'GitVersion'
      inputs:
        script: dotnet-gitversion /output buildserver
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Generate CGManifest'
      inputs:
        filePath: ./Generate-CGManifest.ps1
        targetType: filePath
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy CGManifest Artifacts to Staging'
      inputs:
        Contents: 'cgmanifest.json'
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/cgmanifest/$(os)/$(arch)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        ArtifactName: 'cgmanifest'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/cgmanifest'

    - task: PowerShell@2
      displayName: 'Set BuildTimestamp variable'
      inputs:
        script: |
          $pipelineStartTime = $env:SYSTEM_PIPELINESTARTTIME
          $buildTimestamp = Get-Date -Date $pipelineStartTime -UFormat %s
          Write-Host "##vso[task.setvariable variable=BuildTimestamp]$buildTimestamp"
        targetType: inline

    - task: PowerShell@2
      displayName: 'Generate'
      inputs:
        script: make generate-ci
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        GOOS: '$(os)'
        GOARCH: '$(arch)'

    - task: PowerShell@2
      displayName: 'Build'
      inputs:
        script: make release
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        GOOS: '$(os)'
        GOARCH: '$(arch)'
        VERSION: '$(GitVersion.FullSemVer)'
        BUILD_TIMESTAMP: '$(BuildTimestamp)'

    - task: PowerShell@2
      displayName: 'Sign Windows Binaries'
      inputs:
        script: dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /filelist:$env:BUILD_SOURCESDIRECTORY/.azure/pipelines/filelist-windows.xml
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      condition: and(succeeded(), eq(variables.os, 'windows'), eq(variables.signType, 'real'))

    - task: PowerShell@2
      displayName: 'Sign MacOS Binaries'
      inputs:
        script: |
          zip -ry $env:ARCHIVE_FILE ./bin/
          dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /file:$env:ARCHIVE_FILE /certs:8023
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        ARCHIVE_FILE: '$(Build.SourcesDirectory)/dcp-darwin.zip'
      condition: and(succeeded(), eq(variables.os, 'darwin'), eq(variables.SignType, 'real'))

    - task: PowerShell@2
      displayName: 'Sign MacOS Binaries'
      inputs:
        script: |
          dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /file:$env:ARCHIVE_FILE /certs:8020
          unzip -o $env:ARCHIVE_FILE
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        ARCHIVE_FILE: '$(Build.SourcesDirectory)/dcp-darwin.zip'
      condition: and(succeeded(), eq(variables.os, 'darwin'), eq(variables.SignType, 'real'))

    - task: CopyFiles@2
      displayName: 'Copy Build Artifacts to Staging'
      inputs:
        Contents: '**'
        SourceFolder: '$(Build.SourcesDirectory)/bin/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build/$(os)/$(arch)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

    - task: CopyFiles@2
      displayName: 'Copy License Artifacts to Staging'
      inputs:
        Contents: |
          NOTICE
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build/$(os)/$(arch)'

    - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
      displayName: 'SBOM Generation Task'
      inputs:
        BuildDropPath: '$(Build.ArtifactStagingDirectory)/build/$(os)/$(arch)'
        PackageName: 'Developer Control Plane'
        PackageVersion: '$(GitVersion.MajorMinorPatch)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        ArtifactName: 'build'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/build'

    - task: DotNetCoreCLI@2
      displayName: 'Package NuGet $(os)-$(arch)'
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/.azure/DcpNuGet/DcpNuGet.csproj'
        arguments: -p:TargetPlatform=$(os)-$(arch) -p:BuildDir=$(Build.SourcesDirectory)/bin/ -p:Version=$(GitVersion.SemVer)
      condition: and(succeeded(), eq('${{ parameters.packageNuGet }}', true))

    - task: CopyFiles@2
      displayName: 'Copy NuGet Artifacts to Staging'
      inputs:
        Contents: '*.nupkg'
        SourceFolder: '$(Build.SourcesDirectory)/package/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/nuget'
      condition: and(succeeded(), eq('${{ parameters.packageNuGet }}', true), ne(variables['Build.Reason'], 'PullRequest'))

    - task: PublishBuildArtifacts@1
      displayName: 'Publish NuGet Artifacts'
      inputs:
        ArtifactName: 'nuget'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/nuget'
      condition: and(succeeded(), eq('${{ parameters.packageNuGet }}', true), ne(variables['Build.Reason'], 'PullRequest'))

    - task: ComponentGovernanceComponentDetection@0
      condition: and(succeeded(), notin(variables['Build.Reason'], 'PullRequest'))

    - task: MicroBuildCleanup@1
      condition: succeededOrFailed()

- stage: test
  dependsOn: []
  jobs:
  - job: Test
    strategy:
      matrix:
        linux:
          image: ubuntu-latest
          testCommand: make test-ci
        windows:
          image: windows-latest
          testCommand: make test
        macos:
          image: macos-latest
          testCommand: make test
    pool:
      vmImage: $(image)
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: $(testCommand)
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        TEST_CONTEXT_TIMEOUT: ${{ parameters.testTimeout }} # Increase test timeout to deal with slow tests

- stage: verify
  dependsOn: build
  condition: eq(variables.signType, 'real')
  jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifact: 'build'
        targetPath: '$(Agent.BuildDirectory)/build'

    - task: CodeSign@1
      displayName: 'Verify Windows Signatures'
      inputs:
        Path: '$(Agent.BuildDirectory)/build/windows/'

    - task: PostAnalysis@2
      inputs:
        GdnBreakAllTools: true

  - job: Mac
    pool:
      vmImage: macos-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifact: 'build'
        targetPath: '$(Agent.BuildDirectory)/build'

    - task: Bash@3
      displayName: "Verify MacOS Signatures"
      inputs:
        script: find . -type f -name dcp -o -name dcpd -o -name dcpctrl -o -name traefik | xargs -J % codesign -vvv --strict -R="anchor apple generic and certificate leaf[subject.OU] = $SIGNHASH" %
        targetType: inline
        workingDirectory: '$(Agent.BuildDirectory)/build/darwin/'
      env:
        SIGNHASH: UBF8T346G9

    - task: MicroBuildCleanup@1
      condition: succeededOrFailed()

- stage: release
  dependsOn: verify
  condition: and(notin(variables['Build.Reason'], 'PullRequest'), eq(variables.shouldDeploy, 'true'), eq('${{ parameters.packageNuGet }}', true))
  jobs:
  - deployment: NuGetPublish
    pool: VSEngSS-MicroBuild2022-1ES
    environment: '$(environment)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: NuGetCommand@2
            displayName: 'Push NuGet Packages'
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/nuget/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '$(deployFeed)'
  - deployment: ArcadeManifestBuild
    pool: VSEngSS-MicroBuild2022-1ES
    environment: '$(environment)'
    dependsOn:
    - NuGetPublish
    variables:
    - group: Publish-Build-Assets
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: DotNetCoreInstaller@1
            displayName: 'Install .NET 7.0'
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: DotNetCoreCLI@2
            displayName: 'Build Arcade Manifest'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/.azure/ArcadeManifest/ArcadeManifest.csproj'
              arguments: -t:GenerateAssetManifest -restore -p:NuGetClientNupkgsDirectoryPath=$(Pipeline.Workspace)/nuget/ -p:NuGetFeed=$(feedName) -p:ArtifactsLogDir=$(Build.ArtifactStagingDirectory)/arcade/ -p:MaestroAccessToken=$(MaestroAccessToken) -p:MaestroApiEndpoint=$(MaestroApiEndpoint)
  - deployment: ArcadeManifestPublish
    pool: VSEngSS-MicroBuild2022-1ES
    environment: '$(environment)'
    dependsOn:
    - ArcadeManifestBuild
    condition: and(succeeded(), or(eq(variables.environment, 'dcp-production'), eq(variables.environment, 'dcp-staging'), eq(variables.environment, 'dcp-development')))
    variables:
    - group: Publish-Build-Assets
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: DotNetCoreInstaller@1
            displayName: 'Install .NET 7.0'
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: DotNetCoreCLI@2
            displayName: 'Publish Manifest to Arcade'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/.azure/ArcadeManifest/ArcadeManifest.csproj'
              arguments: -t:PublishAssetManifest -p:Version=$(Build.BuildNumber) -p:RepoRoot=$(Build.SourcesDirectory) -p:ManifestsPath=$(Pipeline.Workspace)/AssetManifests -p:BuildAssetRegistryToken=$(MaestroAccessToken) -p:MaestroApiEndpoint=$(MaestroApiEndpoint)
  - deployment: ArcadeBuildPromote
    pool: VSEngSS-MicroBuild2022-1ES
    environment: '$(environment)'
    dependsOn:
    - ArcadeManifestPublish
    condition: and(succeeded(), or(eq(variables.environment, 'dcp-production'), eq(variables.environment, 'dcp-staging'), eq(variables.environment, 'dcp-development')))
    variables:
    - group: Publish-Build-Assets
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreInstaller@1
            displayName: 'Install .NET 7.0'
            inputs:
              packageType: 'sdk'
              version: '7.0.x'
          - task: PowerShell@2
            displayName: 'Install Darc'
            inputs:
              script: |
                $darcCliPackageName = 'microsoft.dotnet.darc'
                $versionEndpoint = 'https://maestro-prod.westus2.cloudapp.azure.com/api/assets/darc-version?api-version=2019-01-16'
                $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
                $arcadeServicesSource = 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
                Write-Host "Installing Darc CLI version $darcVersion..."
                Write-Host "dotnet tool install $darcCliPackageName --version $darcVersion --add-source '$arcadeServicesSource' -g"
                & dotnet tool install $darcCliPackageName --version $darcVersion --add-source "$arcadeServicesSource" -g
              targetType: inline
          - task: PowerShell@2
            displayName: 'Promote to Channel'
            inputs:
              script: |
                Write-Host 'darc add-build-to-channel --id "$env:BAR_BUILD_ID" --publishing-infra-version 3 --default-channels --source-branch main --bar-uri $env:MAESTRO_API_ENDPOINT'
                darc add-build-to-channel --id "$env:BAR_BUILD_ID" --publishing-infra-version 3 --default-channels --source-branch main --bar-uri $env:MAESTRO_API_ENDPOINT --password $env:MAESTRO_ACCESS_TOKEN --azdev-pat $env:SYSTEM_ACCESSTOKEN
              targetType: inline
            env:
              BAR_BUILD_ID: $(BARBuildId)
              MAESTRO_API_ENDPOINT: $(MaestroApiEndpoint)
              MAESTRO_ACCESS_TOKEN: $(MaestroAccessToken)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
