trigger: none

parameters:
- name: goVersion
  type: string
  default: '1.20.6'

stages:
- stage: build
  jobs:
  - job: Windows
    pool: VSEngSS-MicroBuild2019-1ES
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: ChocolateyToolInstaller@1
      displayName: 'Install Chocolatey'

    - task: PowerShell@2
      displayName: 'Install Tool Dependencies'
      inputs:
        script: choco install make gawk curl golangci-lint -y
        targetType: inline

    - task: PowerShell@2
      displayName: 'Build'
      inputs:
        script: make build
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: make test-ci
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy dcp to Staging'
      inputs:
        Contents: '**'
        SourceFolder: '$(Build.SourcesDirectory)/bin'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/bin'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        ArtifactName: 'build'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/bin'