trigger: none

parameters:
- name: goVersion
  displayName: 'Go Version'
  type: string
  default: '1.20.6'
- name: signType
  displayName: 'Sign Type'
  values:
  - 'none'
  - 'test'
  - 'real'
  default: real
- name: testTimeout
  displayName: 'Test Timeout (minutes)'
  type: number
  default: 6
- name: buildMatrix
  displayName: 'Build Matrix'
  type: object
  default:
  - os: windows
    arch: amd64
  - os: windows
    arch: arm64
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64
  - os: darwin
    arch: amd64
  - os: darwin
    arch: arm64

variables:
  TeamName: 'DCP'

stages:
- stage: build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: MicroBuildSigningPlugin@3
      displayName: 'Install Signing Plugin'
      inputs:
        signType: '${{ parameters.signType }}'
        azureSubscription: 'MicroBuild Signing Task (DevDiv)'
        feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      condition: and(succeeded(), ne(variables.signType, 'none'))

    - task: DotNetCoreInstaller@1
      displayName: 'Install .NET 3.1'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Generate'
      inputs:
        script: make generate
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - ${{ each buildTarget in parameters.buildMatrix }}:
      - task: PowerShell@2
        displayName: 'Build ${{ buildTarget.os }}-${{ buildTarget.arch }}'
        inputs:
          script: make release
          targetType: inline
          workingDirectory: '$(Build.SourcesDirectory)'
        env:
          OUTPUT_BIN: '$(Build.SourcesDirectory)/bin/${{ buildTarget.os }}/${{ buildTarget.arch }}'
          GOOS: '${{ buildTarget.os }}'
          GOARCH: '${{ buildTarget.arch }}'

    - task: PowerShell@2
      displayName: 'Sign Windows Binaries'
      inputs:
        script: dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /filelist:$env:BUILD_SOURCESDIRECTORY/.azure/pipelines/filelist-windows.xml
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      condition: and(succeeded(), eq('${{ parameters.signType }}', 'real'))

    - task: PowerShell@2
      displayName: 'Sign MacOS Binaries'
      inputs:
        script: |
          zip -ry $env:ARCHIVE_FILE ./bin/darwin/
          dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /file:$env:ARCHIVE_FILE /certs:8023
          unzip -o $env:ARCHIVE_FILE
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        ARCHIVE_FILE: '$(Build.SourcesDirectory)/dcp-darwin.zip'
      condition: and(succeeded(), eq('${{ parameters.signType }}', 'real'))

    - task: CopyFiles@2
      displayName: 'Copy Build Artifacts to Staging'
      inputs:
        Contents: '**'
        SourceFolder: '$(Build.SourcesDirectory)/bin/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        ArtifactName: 'build'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/build'

    - task: MicroBuildCleanup@1
      condition: succeededOrFailed()

- stage: test
  dependsOn: []
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: make test-ci
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        TEST_CONTEXT_TIMEOUT: ${{ parameters.testTimeout }} # Increase test timeout to deal with slow tests

- stage: verify
  dependsOn: build
  jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifact: 'build'
        targetPath: '$(Agent.BuildDirectory)/build'

    - task: CodeSign@1
      displayName: 'Verify Windows Signatures'
      inputs:
        Path: '$(Agent.BuildDirectory)/build/windows/'
      condition: and(succeeded(), eq('${{ parameters.signType }}', 'real'))

  - job: Mac
    pool:
      vmImage: macos-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifact: 'build'
        targetPath: '$(Agent.BuildDirectory)/build'

    - task: MicroBuildMacSignVerify@0
      displayName: 'Verify MacOS Signatures'
      inputs:
        Directories: '$(Agent.BuildDirectory)/build/darwin/'
        AppIdentity: 'Developer ID Application: Microsoft Corporation (UBF8T346G9)'
      condition: and(succeeded(), eq('${{ parameters.signType }}', 'real'))
