trigger:
  branches:
    include:
    - main
    - release/*

parameters:
- name: goVersion
  displayName: 'Go Version'
  type: string
  default: '1.20.7'
- name: signType
  displayName: 'Sign Type'
  values:
  - 'none'
  - 'test'
  - 'real'
  default: real
- name: testTimeout
  displayName: 'Test Timeout (minutes)'
  type: number
  default: 3
- name: packageNuGet
  displayName: 'Package NuGet(s)'
  type: boolean
  default: true

variables:
  TeamName: 'DCP'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    signType: 'none'
    pullRequest: true
  ${{ else }}:
    signType: ${{ parameters.signType }}
    pullRequest: false

stages:
- stage: build
  jobs:
  - job: Build
    strategy:
      matrix:
        windows-x86:
          os: windows
          arch: '386'
          extension: .exe
          isUnix: false
        windows-amd64:
          os: windows
          arch: amd64
          extension: .exe
          isUnix: false
        windows-arm64:
          os: windows
          arch: arm64
          extension: .exe
          isUnix: false
        linux-amd64:
          os: linux
          arch: amd64
          extension: ''
          isUnix: true
        linux-arm64:
          os: linux
          arch: arm64
          extension: ''
          isUnix: true
        macos-amd64:
          os: darwin
          arch: amd64
          extension: ''
          isUnix: true
        macos-arm64:
          os: darwin
          arch: arm64
          platform: osx-x64
          extension: ''
          isUnix: true
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - task: MicroBuildSigningPlugin@3
      displayName: 'Install Signing Plugin'
      inputs:
        signType: '$(signType)'
        azureSubscription: 'MicroBuild Signing Task (DevDiv)'
        feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      condition: and(succeeded(), ne(variables.signType, 'none'))

    - task: DotNetCoreInstaller@1
      displayName: 'Install .NET 3.1'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: DotNetCoreInstaller@1
      displayName: 'Install .NET 7.0'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: PowerShell@2
      displayName: 'Install GitVersion'
      inputs:
        script: dotnet tool install --global GitVersion.Tool --version "5.*"
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PowerShell@2
      displayName: 'GitVersion'
      inputs:
        script: dotnet-gitversion /output buildserver
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Generate CGManifest'
      inputs:
        filePath: ./Generate-CGManifest.ps1
        targetType: filePath
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy CGManifest Artifacts to Staging'
      inputs:
        Contents: 'cgmanifest.json'
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/cgmanifest/$(os)/$(arch)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        ArtifactName: 'cgmanifest'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/cgmanifest'

    - task: PowerShell@2
      displayName: 'Set BuildTimestamp variable'
      inputs:
        script: |
          $pipelineStartTime = $env:SYSTEM_PIPELINESTARTTIME
          $buildTimestamp = Get-Date -Date $pipelineStartTime -UFormat %s
          Write-Host "##vso[task.setvariable variable=BuildTimestamp]$buildTimestamp"
        targetType: inline

    - task: PowerShell@2
      displayName: 'Generate'
      inputs:
        script: make generate
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PowerShell@2
      displayName: 'Build'
      inputs:
        script: make release
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        GOOS: '$(os)'
        GOARCH: '$(arch)'
        VERSION: '$(GitVersion.FullSemVer)'
        BUILD_TIMESTAMP: '$(BuildTimestamp)'

    - task: PowerShell@2
      displayName: 'Download traefik for $(os)-$(arch)'
      inputs:
        script: make download-proxy
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        GOOS: '$(os)'
        GOARCH: '$(arch)'

    - ${{ if eq(variables.os, 'windows') }}:
      - task: PowerShell@2
        displayName: 'Sign Windows Binaries'
        inputs:
          script: dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /filelist:$env:BUILD_SOURCESDIRECTORY/.azure/pipelines/filelist-windows.xml
          targetType: inline
          workingDirectory: '$(Build.SourcesDirectory)'
        condition: and(succeeded(), eq(variables.signType, 'real'))
    - ${{ elseif eq(variables.os, 'darwin') }}:
      - task: PowerShell@2
        displayName: 'Sign MacOS Binaries'
        inputs:
          script: |
            zip -ry $env:ARCHIVE_FILE ./bin/
            dotnet $env:MBSIGN_APPFOLDER/DDSignFiles.dll -- /file:$env:ARCHIVE_FILE /certs:8023
            unzip -o $env:ARCHIVE_FILE
          targetType: inline
          workingDirectory: '$(Build.SourcesDirectory)'
        env:
          ARCHIVE_FILE: '$(Build.SourcesDirectory)/dcp-darwin.zip'
        condition: and(succeeded(), eq(variables.SignType, 'real'))

    - task: CopyFiles@2
      displayName: 'Copy Build Artifacts to Staging'
      inputs:
        Contents: '**'
        SourceFolder: '$(Build.SourcesDirectory)/bin/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build/$(os)/$(arch)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        ArtifactName: 'build'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/build'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

    - task: DotNetCoreCLI@2
      displayName: 'Package NuGet $(os)-$(arch)'
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/.azure/pipelines/NuGet.csproj'
        arguments: -p:TargetPlatform=$(os)-$(arch) -p:BuildDir=$(Build.SourcesDirectory)/bin/;IncludeUnixFilePermissions=$(isUnix) -p:Version=$(GitVersion.SemVer)
      condition: and(succeeded(), eq('${{ parameters.packageNuGet }}', true))

    - task: CopyFiles@2
      displayName: 'Copy Build Artifacts to Staging'
      inputs:
        Contents: '*.nupkg'
        SourceFolder: '$(Build.SourcesDirectory)/package/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/nuget'
      condition: and(succeeded(), eq('${{ parameters.packageNuGet }}', true), ne(variables['Build.Reason'], 'PullRequest'))

    - task: PublishBuildArtifacts@1
      displayName: 'Publish NuGet Artifacts'
      inputs:
        ArtifactName: 'nuget'
        publishLocation: 'Container'
        PathToPublish: '$(Build.ArtifactStagingDirectory)/nuget'
      condition: and(succeeded(), eq('${{ parameters.packageNuGet }}', true), ne(variables['Build.Reason'], 'PullRequest'))

    - task: MicroBuildCleanup@1
      condition: succeededOrFailed()

- stage: test
  dependsOn: []
  jobs:
  - job: Test
    strategy:
      matrix:
        linux:
          image: ubuntu-latest
          testCommand: make test-ci
        windows:
          image: windows-latest
          testCommand: make test
        macos:
          image: macos-latest
          testCommand: make test
    pool:
      vmImage: $(image)
    steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '${{ parameters.goVersion }}'

    - task: PowerShell@2
      displayName: 'Test'
      inputs:
        script: $(testCommand)
        targetType: inline
        workingDirectory: '$(Build.SourcesDirectory)'
      env:
        TEST_CONTEXT_TIMEOUT: ${{ parameters.testTimeout }} # Increase test timeout to deal with slow tests

- stage: verify
  dependsOn: build
  condition: eq(variables.signType, 'real')
  jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifact: 'build'
        targetPath: '$(Agent.BuildDirectory)/build'

    - task: CodeSign@1
      displayName: 'Verify Windows Signatures'
      inputs:
        Path: '$(Agent.BuildDirectory)/build/windows/'

  - job: Mac
    pool:
      vmImage: macos-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifact: 'build'
        targetPath: '$(Agent.BuildDirectory)/build'

    - task: MicroBuildMacSignVerify@0
      displayName: 'Verify MacOS Signatures'
      inputs:
        Directories: '$(Agent.BuildDirectory)/build/darwin/'
        AppIdentity: 'Developer ID Application: Microsoft Corporation (UBF8T346G9)'

    - task: MicroBuildCleanup@1
      condition: succeededOrFailed()