trigger: none

parameters:
- name: signType
  displayName: 'Sign Type'
  values:
  - 'none'
  - 'test'
  - 'real'
  default: real
- name: testTimeout
  displayName: 'Test Timeout (seconds)'
  type: number
  default: 180

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: common-variables.yml@self

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    featureFlags:
      disableNetworkIsolation: true
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
    containers:
      linux_build_container:
        image: 'mcr.microsoft.com/oss/go/microsoft/golang:1.23-bullseye'
        options: --name $(BuildContainerName)
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
      policheck:
        enabled: true
      tsa:
        enabled: true
        config:
          codebaseName: usvc-apiserver_$(Build.SourceBranchName)
          notificationAliases: $(TsaNotificationAliases)
          codebaseAdmins: $(TsaCodebaseAdmins)
          instanceUrl: $(TsaInstanceUrl)
          projectName: $(TsaProjectName)
          areaPath: $(TsaAreaPath)
          iterationPath: $(TsaIterationPath)
          allTools: true
    stages:
    - template: common-build.yml@self
      parameters:
        signType: ${{ parameters.signType}}
        testTimeout: ${{ parameters.testTimeout}}
