trigger: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: common-variables.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool: # Set VSEngSS-MicroBuild2022-1ES Windows pool as default for the SDL tasks
      name: VSEngSS-MicroBuild2022-1ES
      os: windows
    stages:
    - template: common-build.yml@self
      parameters:
        goVersion: '1.21.0'
        signType: none
