trigger: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: common-variables.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
    containers:
      linux_build_container:
        image: 'mcr.microsoft.com/oss/go/microsoft/golang:1.24-bullseye'
        options: --name $(BuildContainerName)
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
      policheck:
        enabled: true
    featureFlags:
      golang:
        internalModuleProxy:
          enabled: true
    stages:
    - template: common-build.yml@self
      parameters:
        signType: none
