linters-settings:
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true
    disable:
      - loopclosure # https://go.dev/doc/faq#closures_and_goroutines, we are using Go 1.22+ now
