//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Code generated by openapi-gen. DO NOT EDIT.

package v1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AmbientEnvironment) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.AmbientEnvironment"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CleanupResource) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.CleanupResource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Container) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.Container"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerBuildContext) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerBuildContext"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerBuildSecret) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerBuildSecret"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerExec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerExec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerExecList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerExecList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerExecLogResource) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerExecLogResource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerExecSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerExecSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerExecStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerExecStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerLabel) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerLabel"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerLogResource) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerLogResource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetwork) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetwork"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkConnection) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkConnection"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkConnectionConfig) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkConnectionConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkConnectionList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkConnectionList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkConnectionSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkConnectionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkTunnelProxy) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkTunnelProxy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkTunnelProxyList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkTunnelProxyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkTunnelProxySpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkTunnelProxySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkTunnelProxyStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerNetworkTunnelProxyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerPemCertificates) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerPemCertificates"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerPort) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerVolume) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerVolume"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerVolumeList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerVolumeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerVolumeSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerVolumeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerVolumeStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ContainerVolumeStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CreateFileSystem) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.CreateFileSystem"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Endpoint) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.Endpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.EndpointList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.EndpointSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.EndpointStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EnvVar) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.EnvVar"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Executable) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.Executable"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableLogResource) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableLogResource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutablePemCertificates) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutablePemCertificates"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableProbe) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableProbe"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableReplicaSet) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableReplicaSet"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableReplicaSetList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableReplicaSetList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableReplicaSetSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableReplicaSetSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableReplicaSetStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableReplicaSetStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExecutableTemplate) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ExecutableTemplate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FileSystemEntry) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.FileSystemEntry"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HealthProbe) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.HealthProbe"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HealthProbeResult) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.HealthProbeResult"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HealthProbeSchedule) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.HealthProbeSchedule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HttpHeader) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.HttpHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HttpProbe) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.HttpProbe"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageLayer) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ImageLayer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LogOptions) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.LogOptions"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LogOptionsList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.LogOptionsList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LogStorage) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.LogStorage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LogStreamer) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.LogStreamer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LogStreamerList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.LogStreamerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PemCertificate) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.PemCertificate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ResourceWatcherEvent) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ResourceWatcherEvent"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Service) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.Service"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ServiceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ServiceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.ServiceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TerminalSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.TerminalSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TunnelConfiguration) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.TunnelConfiguration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TunnelStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.TunnelStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeMount) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v1.VolumeMount"
}
