//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Code generated by openapi-gen. DO NOT EDIT.

package commonapi

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EnvVar) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/pkg/commonapi.EnvVar"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Label) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/pkg/commonapi.Label"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamespacedNameWithKind) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/pkg/commonapi.NamespacedNameWithKind"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ServiceProducer) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/pkg/commonapi.ServiceProducer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UnexpectedObjectStateError) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/pkg/commonapi.UnexpectedObjectStateError"
}
