//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Code generated by openapi-gen. DO NOT EDIT.

package v2

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerBuildContext) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.ContainerBuildContext"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerBuildSecret) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.ContainerBuildSecret"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerNetworkConnectionConfig) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.ContainerNetworkConnectionConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerPort) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.ContainerPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CreateFileSystem) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.CreateFileSystem"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FileSystemEntry) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.FileSystemEntry"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Namespace) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.Namespace"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamespaceList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.NamespaceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamespaceStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.NamespaceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainer) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerConfig) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerImage) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerImage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerImageConfig) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerImageConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerImageList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerImageList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerImageSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerImageSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerImageStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerImageStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerPortMapping) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerPortMapping"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalContainerStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalContainerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalNetwork) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalNetwork"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalNetworkList) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalNetworkList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalNetworkSpec) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalNetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PhysicalNetworkStatus) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.PhysicalNetworkStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeMount) OpenAPIModelName() string {
	return "github.com/microsoft/dcp/api/v2.VolumeMount"
}
