name: Check Generated Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*
      - production

permissions:
  contents: read
  pull-requests: write

env:
  GOPRIVATE: github.com/microsoft/usvc-*,github.com/microsoft/dcp

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          generateCommand: make generate-ci
    name: Validate ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup Go environment
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version-file: 'go.mod'
        architecture: 'x64'

    - name: Validate
      run: ${{ matrix.generateCommand }}

    - name: Verify generated files up-to-date
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        script: |
          const result = await exec.getExecOutput('git status -s');
          if (result.exitCode != 0 || result.stdout.trim() != '') {
            const diffResult = await exec.getExecOutput('git diff')
            core.setFailed('Generated files not up-to-date. Please run make generate-ci and commit the latest versions. The output of git diff command is:' + diffResult.stdout.trim())
          }
      if: matrix.os != 'windows-latest'
