name: Check Generated Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*
      - production

permissions:
  contents: read
  pull-requests: write

env:
  GOPRIVATE: github.com/microsoft/usvc-*,github.com/microsoft/dcp

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          generateCommand: make generate-ci
    name: Validate ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Go environment
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
        architecture: 'x64'

    - name: Validate
      run: ${{ matrix.generateCommand }}

    - name: Verify generated files up-to-date
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          const result = await exec.getExecOutput('git status -s');
          if (result.exitCode != 0 || result.stdout.trim() != '') {
            const diffResult = await exec.getExecOutput('git diff')
            core.setFailed('Generated files not up-to-date. Please run make generate-ci and commit the latest versions. The output of git diff command is:' + diffResult.stdout.trim())
          }
      if: matrix.os != 'windows-latest'
